<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD 검사 -->
<!-- 사용 개수 지정  
- student : 1개
- student? : 0 또는 1
- student* : 0개 이상
- student+ : 1개 이상
-->
<!DOCTYPE students [
<!ELEMENT students (student*)>
<!ELEMENT student (name,age?,tel,email,intro?,working?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT tel (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT working EMPTY>
]>

<students>
  <student>
    <name>홍길동</name>
    <age>20</age>
    <tel>111</tel>
    <email>hong@test.com</email>
    <intro>학생이다.</intro>
    <working></working>
  </student>
  <student>
    <name>홍길동</name>
    <tel>111</tel>
    <email>hong@test.com</email>
  </student> 
<!-- 자식 엘리먼트의 순서는 반드시 지켜야 한다. -->
<!--   
  <student>
    <tel>111</tel>
    <name>홍길동</name>
    <email>hong@test.com</email>
  </student> 
--> 

<!-- EMPTY 엘리먼트의 콘튼츠는 없어야 한다. -->
<!--  
  <student>
    <name>홍길동</name>
    <tel>111</tel>
    <email>hong@test.com</email>
    <working>yes</working>
  </student> 
-->  
  <student>
    <name>홍길동</name>
    <tel>111</tel>
    <email>hong@test.com</email>
    <working/> <!-- 끝태그 생략 가능. 단 시작태그에 표시해야 한다. -->
  </student> 
</students>










